apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "s3-proxy.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "s3-proxy.name" . }}
    helm.sh/chart: {{ include "s3-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yaml: {{ .Values.config | quote }}
